package hetu.seth;

public class EgmLicense {

public static final String Text = 
    "/********************************************************************************\\\n"
  + "**                                                                              **\n"
  + "**  Copyright (C) 2008 Josh Ventura                                             **\n"
  + "**                                                                              **\n"
  + "**  This file is a part of the ENIGMA Development Environment.                  **\n"
  + "**                                                                              **\n"
  + "**                                                                              **\n"
  + "**  ENIGMA is free software: you can redistribute it and/or modify it under the **\n"
  + "**  terms of the GNU General Public License as published by the Free Software   **\n"
  + "**  Foundation, version 3 of the license or any later version.                  **\n"
  + "**                                                                              **\n"
  + "**  This application and its source code is distributed AS-IS, WITHOUT ANY      **\n"
  + "**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **\n"
  + "**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **\n"
  + "**  details.                                                                    **\n"
  + "**                                                                              **\n"
  + "**  You should have recieved a copy of the GNU General Public License along     **\n"
  + "**  with this code. If not, see <http://www.gnu.org/licenses/>                  **\n"
  + "**                                                                              **\n"
  + "**  ENIGMA is an environment designed to create games and other programs with a **\n"
  + "**  high-level, fully compilable language. Developers of ENIGMA or anything     **\n"
  + "**  associated with ENIGMA are in no way responsible for its users or           **\n"
  + "**  applications created by its users, or damages caused by the environment     **\n"
  + "**  or programs made in the environment.                                        **\n"
  + "**                                                                              **\n"
  + "\\********************************************************************************/\n\n"
  + "//This file was generated by the ENIGMA Development Environment (new parser).\n"
  + "//You should almost certainly not modify it by hand unless you're feeling dangerous.\n\n";
}
